import Head from 'next/head';

import Navigation from '@wiki/containers/Navigation';

export default function Home() {
  return (
    <>
      <Head>
        <title>Rick & Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-full p-2 bg-gray-100">
        Home
      </div>
    </>
  );
}
