import Head from 'next/head';

import Navigation from '@core/Navigation';

export default function Home() {
  return (
    <>
      <Head>
        <title>Rick & Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen bg-gray-100">
        <Navigation />
      </div>
    </>
  );
}
